# Generated by Django 4.1.1 on 2022-09-28 19:19

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=80)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calories_per_serving', models.DecimalField(decimal_places=1, max_digits=6)),
                ('food_description', models.TextField()),
                ('recipe_link', models.CharField(max_length=200)),
                ('food_image', pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='foodImages')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=11)),
            ],
        ),
    ]
